name = "xugou-app"
main = "backend/src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

minify = true # 生产环境压缩代码

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db" # 使用占位符
database_id = "1acb4772-323d-496d-9fb6-03f4de6b2755" # 使用占位符

[assets]
binding = "ASSETS"
directory = "frontend/dist"
not_found_handling = "single-page-application"

[version_metadata]
binding = "CF_VERSION_METADATA"
